"""followers in association table and User class

Revision ID: 48add3c27ee5
Revises: e45a609d9f27
Create Date: 2020-06-02 14:56:10.945376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48add3c27ee5'
down_revision = 'e45a609d9f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
