"""add song_link to database

Revision ID: 62b1c9c5e9da
Revises: 17ec547744c6
Create Date: 2020-12-21 09:25:09.169774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b1c9c5e9da'
down_revision = '17ec547744c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('song_link', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'song_link')
    # ### end Alembic commands ###
